### ISSUE TITLE
Trying to run the first example.

### ISSUE THREAD

**Issue by gmcavins** [dskrypa/cli_command_parser#1]
Installed python 3.9 and 3.10 trying to run cli_command_parser/tree/main/examples)/action_with_args.py.
 I get the following error:

Traceback (most recent call last):
  File "./bin/test.py", line 3, in <module>
    from cli_command_parser import Command, Action, Positional
  File "/Users/gmcavins/work/sboxes/p1-stack-utils/__pypackages__/3.10/lib/cli_command_parser/__init__.py", line 7, in <module>
    from .config import CommandConfig
  File "/Users/gmcavins/work/sboxes/p1-stack-utils/__pypackages__/3.10/lib/cli_command_parser/config.py", line 21
    multiple_action_flags: Bool = True
                         ^
SyntaxError: invalid syntax

I must be doing something wrong, thoughts.

**Comment by dskrypa** [comment]
Can you please provide some additional details - how exactly are you invoking it?  Are you running it from bash, cmd, or powershell?  Are you relying on the shebang and running it directly, or are you calling the script as `python action_with_args.py`?  Are you using a venv?

**Comment by gmcavins** [comment]
I figured this issue out. I am trying to use pdm and had it configured incorrectly.
So, this can be closed.  I have moved on to trying to add Parameters. It would be nice if there were more examples.

So, far I like the API.

**Comment by dskrypa** [comment]
I got distracted by some other stuff, but would like to / will try to get back to this soon, and will push more examples that I have been working on.  Glad you like it!

**Comment by dskrypa** [comment]
A before/after example that is 90%+ done:
Before: https://github.com/dskrypa/music_manager/blob/master/lib/music/cli/plex_manager.py
After: https://github.com/dskrypa/music_manager/blob/master/lib/music/cli/plex_manager_new.py

**Comment by dskrypa** [comment]
Documentation has been significantly expanded:
https://dskrypa.github.io/cli_command_parser/index.html
