### ISSUE TITLE
Requiring both long and short opts.

### ISSUE THREAD

**Issue by gmcavins** [dskrypa/cli_command_parser#48]
All release since 2023.5.13:

The code in file: cli_command_parser/parameters/option_strings.py at
   ~192 line in function "_split_options" seems to require that both the long and short be specified.  

Trace:
File "/usr/local/lib/python3.9/site-packages/cli_command_parser/parameters/option_strings.py", line 31, in __init__
    long_opts, short_opts = _split_options(option_strs)
  File "/usr/local/lib/python3.9/site-packages/cli_command_parser/parameters/option_strings.py", line 204, in _split_options
    raise ParameterDefinitionError(
cli_command_parser.exceptions.ParameterDefinitionError: Bad option(s) - they must start with '--' or '-', may not end with '-', and may not contain '=': 

ecample 1:
  (Pdb) opt_strs
  (. '-v', '')

example 2:
  (Pdb} opt_strs
  ('', '--no-color')

Was this an intended breaking change?

**Comment by dskrypa** [comment]
Requiring both was not intended, and I have not encountered that issue.  I have a fair number of optional params in commands with no short option, and I have some test cases for a short with no long, but I don't often use that myself.

Can you please provide a minimal reproducible example, with at least the full Option/Flag/etc lines that are triggering this issue so I can test them?  I.e., `no_color = Flag(...)`, with all of the arguments being passed to it.

**Comment by dskrypa** [comment]
Ahh, are you passing an empty string for the value you're not using?  Before, [it would iterate over all option strings twice](https://github.com/dskrypa/cli_command_parser/blob/2023.05.08/lib/cli_command_parser/parameters/option_strings.py#L31-L32) - once to pick out the long options, then again to pick out the short options.  There was also a third loop over the option strings to check for bad ones.  Now, that `_split_options` function handles all 3 cases in one pass.

The 2 loops that specifically picked out long or short options would essentially silently filter out any empty strings, and the check for bad option strings did not raise an exception on an empty string.

I will add a truthiness check in `_split_options` to filter out empty strings, and will add test cases for it.  In the meantime, as long as you don't pass an empty string for either, it should work as expected.  I still need to update the documentation for the `name_mode` arg for Option-like parameters, but you can use `name_mode=None` on a given Option/Flag/etc with a short option string to [prevent it from adding an automatic long form](https://dskrypa.github.io/cli_command_parser/api/cli_command_parser.config.html#cli_command_parser.config.OptionNameMode).

**Comment by gmcavins** [comment]
Yes, I am creating the options via a dictionary which has one or both options. So, the check should work for me. Thanks

**Comment by dskrypa** [comment]
The latest release (2023.05.19) should fix this.  Please let me know if there is still an issue.

**Comment by dskrypa** [comment]
Please let me know if that fixed it!  There have been a couple releases since then as well, and all should hopefully work for you.

**Comment by gmcavins** [comment]
The fix you made worked for me!

Thanks, Mike
